import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { motion } from 'framer-motion';
import {
  CheckCircle,
  AlertCircle,
  Download,
  Home,
  Calendar,
  User,
  Baby,
} from 'lucide-react';
import { Button, Card, StatusBadge } from '../components/ui';
import qchatAPI from '../services/qchat-api';
import useSessionStore from '../store/sessionStore';
import { RiskLevel } from '../types/api.types';
import type { QChatReport } from '../types/api.types';

const QChatReportPage: React.FC = () => {
  const { token } = useParams<{ token: string }>();
  const navigate = useNavigate();
  const { t } = useTranslation();

  const [report, setReport] = useState<QChatReport | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Session store
  const { updateSessionStatus, updateSessionScore } = useSessionStore();

  useEffect(() => {
    const loadReport = async () => {
      if (!token) {
        setError('No session token provided');
        setIsLoading(false);
        return;
      }

      try {
        const data = await qchatAPI.getReport(token);
        setReport(data);
        
        // Update session store with completed status and score
        updateSessionStatus('completed');
        
        // Map risk_level string to RiskLevel enum
        let riskLevel: RiskLevel = RiskLevel.LOW;
        if (data.risk_level === 'high') {
          riskLevel = RiskLevel.HIGH;
        } else if (data.risk_level === 'medium') {
          riskLevel = RiskLevel.MEDIUM;
        }
        updateSessionScore(data.total_score, riskLevel);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load report');
      } finally {
        setIsLoading(false);
      }
    };

    loadReport();
  }, [token, updateSessionStatus, updateSessionScore]);

  const handleDownload = () => {
    if (!report) return;

    const divider = '='.repeat(70);
    const separator = '-'.repeat(70);
    const completedDate = new Date(report.completed_at).toLocaleString();

    // Create a well-formatted text report
    const reportText = `
${divider}
               Q-CHAT-10 SCREENING REPORT
        Quantitative Checklist for Autism in Toddlers
${divider}

CHILD INFORMATION
${separator}
Name:              ${report.child_name}
Age:               ${report.child_age_months} months
${report.parent_name ? `Parent/Guardian:   ${report.parent_name}\n` : ''}Date Completed:    ${completedDate}
Session Token:     ${report.session_token}

ASSESSMENT RESULTS
${separator}
Total Score:       ${report.total_score} / ${report.max_score}
Risk Assessment:   ${report.risk_level.toUpperCase()}
Referral Status:   ${report.recommend_referral ? 'RECOMMENDED' : 'NOT RECOMMENDED'}
Threshold:         > 3 points indicates referral recommended

${report.recommend_referral ? `⚠️  ATTENTION: Score indicates referral for further evaluation` : `✓  Score indicates low risk - continue monitoring development`}

RECOMMENDATIONS
${separator}
${report.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n\n')}

DETAILED QUESTION BREAKDOWN
${separator}

${report.answers.map((ans) => {
  const pointStatus = ans.scored_point ? '● SCORED (1 point)' : '○ No point';
  return `Question ${ans.question_number}
Selected: ${ans.selected_option} - ${ans.option_label}
Result:   ${pointStatus}
${separator}`;
}).join('\n')}

DISCLAIMER
${separator}
This screening tool is not a diagnosis. A comprehensive evaluation by
a qualified healthcare professional is needed for clinical diagnosis.
The Q-CHAT-10 is designed to identify toddlers (18-24 months) who may
benefit from further developmental assessment.

${divider}
Generated by Q-CHAT-10 Screening Tool
Report Date: ${new Date().toLocaleString()}
${divider}
    `.trim();

    // Create and download file
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const fileName = `QCHAT-Report-${report.child_name.replace(/\s+/g, '_')}-${new Date().toISOString().split('T')[0]}.txt`;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4"></div>
          <p className="text-gray-600">{t('common.loading')}</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <Card padding="lg" className="max-w-md w-full text-center">
          <AlertCircle className="w-16 h-16 text-danger-500 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            {t('errors.sessionNotFound')}
          </h2>
          <p className="text-gray-600 mb-6">{error || 'Unable to load report'}</p>
          <Button onClick={() => navigate('/')} variant="primary">
            {t('nav.home')}
          </Button>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <motion.div
          className="text-center mb-8"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <h1 className="text-4xl font-bold text-gray-900 mb-3">
            {t('qchat.report.title')}
          </h1>
          <p className="text-gray-600">
            {t('qchat.report.completedAt')}: {new Date(report.completed_at).toLocaleString()}
          </p>
        </motion.div>

        {/* Child Information */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
        >
          <Card padding="lg" className="mb-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">
              Child Information
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="flex items-center gap-3">
                <Baby className="text-primary-500" size={20} />
                <div>
                  <p className="text-sm text-gray-500">Child Name</p>
                  <p className="font-semibold text-gray-900">{report.child_name}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Calendar className="text-primary-500" size={20} />
                <div>
                  <p className="text-sm text-gray-500">Age</p>
                  <p className="font-semibold text-gray-900">{report.child_age_months} months</p>
                </div>
              </div>
              {report.parent_name && (
                <div className="flex items-center gap-3">
                  <User className="text-primary-500" size={20} />
                  <div>
                    <p className="text-sm text-gray-500">Parent/Guardian</p>
                    <p className="font-semibold text-gray-900">{report.parent_name}</p>
                  </div>
                </div>
              )}
            </div>
          </Card>
        </motion.div>

        {/* Score Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <Card
            padding="lg"
            className={`mb-6 ${
              report.recommend_referral
                ? 'border-2 border-warning-400 bg-warning-50'
                : 'border-2 border-success-400 bg-success-50'
            }`}
          >
            <div className="text-center">
              {report.recommend_referral ? (
                <AlertCircle className="w-16 h-16 text-warning-600 mx-auto mb-4" />
              ) : (
                <CheckCircle className="w-16 h-16 text-success-600 mx-auto mb-4" />
              )}

              <h2 className="text-3xl font-bold text-gray-900 mb-2">
                {t('qchat.report.score')}: {report.total_score}/{report.max_score}
              </h2>

              <div className="flex items-center justify-center gap-3 mb-4">
                <span
                  className={`text-lg font-semibold ${
                    report.recommend_referral ? 'text-warning-700' : 'text-success-700'
                  }`}
                >
                  {report.recommend_referral ? t('qchat.report.high') : t('qchat.report.low')}
                </span>
              </div>

              <p className="text-sm text-gray-600">
                {t('qchat.report.threshold')}
              </p>
            </div>
          </Card>
        </motion.div>

        {/* Recommendations */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <Card padding="lg" className="mb-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">
              {t('qchat.report.recommendations')}
            </h2>
            <ul className="space-y-3">
              {report.recommendations.map((recommendation, index) => (
                <li key={index} className="flex gap-3">
                  <span className="text-primary-600 font-semibold flex-shrink-0">
                    {index + 1}.
                  </span>
                  <span className="text-gray-700">{recommendation}</span>
                </li>
              ))}
            </ul>
          </Card>
        </motion.div>

        {/* Answer Breakdown */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <Card padding="lg" className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">
              {t('qchat.report.answerBreakdown')}
            </h2>
            <div className="space-y-3">
              {report.answers.map((answer) => (
                <div
                  key={answer.question_number}
                  className={`p-4 rounded-lg border-2 ${
                    answer.scored_point
                      ? 'border-warning-300 bg-warning-50'
                      : 'border-gray-200 bg-white'
                  }`}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <span className="font-bold text-gray-900">
                          Q{answer.question_number}
                        </span>
                        <span
                          className={`text-xs px-2 py-1 rounded-full font-medium ${
                            answer.scored_point
                              ? 'bg-warning-200 text-warning-800'
                              : 'bg-gray-200 text-gray-700'
                          }`}
                        >
                          {answer.scored_point
                            ? t('qchat.report.scoredPoint')
                            : t('qchat.report.noPoint')}
                        </span>
                      </div>
                      <p className="text-gray-700 mb-1">
                        <span className="font-semibold">{answer.selected_option}:</span>{' '}
                        {answer.option_label}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </motion.div>

        {/* Actions */}
        <motion.div
          className="flex flex-col sm:flex-row gap-4 justify-center items-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
        >
          <Button
            onClick={handleDownload}
            variant="primary"
            size="lg"
            className="relative overflow-hidden group bg-gradient-to-r from-primary-600 to-primary-700 hover:from-primary-700 hover:to-primary-800 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105"
          >
            <span className="relative z-10 flex items-center gap-2">
              <Download size={20} className="animate-bounce group-hover:animate-none" />
              {t('history.downloadReport')}
            </span>
            <div className="absolute inset-0 bg-white opacity-0 group-hover:opacity-10 transition-opacity duration-300"></div>
          </Button>
          <Button
            onClick={() => navigate('/')}
            variant="outline"
            size="lg"
            leftIcon={<Home size={20} />}
            className="hover:bg-gray-50 transition-colors duration-200"
          >
            {t('nav.home')}
          </Button>
        </motion.div>
      </div>
    </div>
  );
};

export default QChatReportPage;
